php53:
    image: php53
    environment:
        PHP_SITE_NAME: dev
    volumes:
        - /Users/ray/git_repos/nyu-law/drupal/:/var/www/html

apache:
    image: apache
    volumes_from:
        - php53
    ports:
        - "49170:80"
        - "49172:443"
    hostname: development
